---
- hosts: all
  gather_facts: false
  tasks:
    - name: "copy docker-compose.yml"
      copy:
        src: "docker-compose.yml"
        dest: "/opt/docker/notes_system/docker-compose.yml"
        owner: "karapetov"
        group: "karapetov"
        mode: "0644"