---
- hosts: all
  gather_facts: true
  vars:
    app_path: /opt/notes_system/api_service
  tasks:
    - name: "create {{ app_path }}/"
      file:
        path: "{{ app_path }}/"
        state: "directory"
        owner: "noteadmin"
        group: "noteadmin"
        mode: 0775
      become: yes
      become_method: sudo

    - name: pwd
      command: pwd
      register: pwwd
      delegate_to: 127.0.0.1
    - debug: msg="{{ pwwd.stdout }}"

    - name: ls -la
      command: ls -la
      register: liist
      delegate_to: 127.0.0.1
    - debug: msg="{{ liist.stdout }}"

    - name: "copy docker-compose.yml"
      copy:
        src: "api_service/docker-compose.yml"
        dest: "{{ app_path }}/docker-compose.yml"
        owner: "noteadmin"
        group: "noteadmin"
        mode: "0644"

    - name: "stop services"
      shell: docker-compose -f {{ app_path }}/docker-compose.yml stop

    - name: "pull images"
      shell: docker-compose -f {{ app_path }}/docker-compose.yml pull

    - name: "start services"
      shell: docker-compose -f {{ app_path }}/docker-compose.yml up -d