---
- hosts: all
  gather_facts: true
  vars:
    app_path: /opt/notes_system/api_service
    user: noteadmin
    group: noteadmin
    docker_compose_file: docker-compose.yml
  tasks:
    - name: "create {{ app_path }}/"
      file:
        path: "{{ app_path }}/"
        state: "directory"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0775
      become: yes
      become_method: sudo

    - name: "copy {{ docker_compose_file }}"
      copy:
        src: "{{ docker_compose_file }}"
        dest: "{{ app_path }}/{{ docker_compose_file }}"
        owner: "{{ user }}"
        group: "{{ group }}"
        mode: 0644
      become: yes
      become_method: sudo

    - name: "stop services"
      shell: docker-compose -f {{ app_path }}/{{ docker_compose_file }} stop

    - name: "pull images"
      shell: docker-compose -f {{ app_path }}/{{ docker_compose_file }} pull

    - name: "start services"
      shell: docker-compose -f {{ app_path }}/{{ docker_compose_file }} up -d