---

is_debug: true
listen:
  type: port
  bind_ip: localhost
  port: 10003
mongodb:
  host: ns-ts-mongodb
  port: 27017
  username: nsuser
  password: nsuser
  auth_db: admin
  database: notes_system
  collection: tags